dist: xenial
language: python
python:
  - "3.6.3"
install:
  - pip3 install netmiko
  - pip3 install ryu
  - git clone --depth=50 --branch=master https://github.com/mininet/mininet.git mininet/mininet
script: python3 test.py
branches:
  only:
    - master
